/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetDotjsRouteImport } from './routes/widget[.]js'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetBotIdRouteImport } from './routes/widget.$botId'
import { Route as EmbedBotIdRouteImport } from './routes/embed.$botId'
import { Route as ChatBotIdRouteImport } from './routes/chat.$botId'
import { Route as BuilderBotIdRouteImport } from './routes/builder.$botId'
import { Route as BotBotIdRouteImport } from './routes/bot.$botId'

const WidgetDotjsRoute = WidgetDotjsRouteImport.update({
  id: '/widget.js',
  path: '/widget.js',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetBotIdRoute = WidgetBotIdRouteImport.update({
  id: '/widget/$botId',
  path: '/widget/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedBotIdRoute = EmbedBotIdRouteImport.update({
  id: '/embed/$botId',
  path: '/embed/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatBotIdRoute = ChatBotIdRouteImport.update({
  id: '/chat/$botId',
  path: '/chat/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderBotIdRoute = BuilderBotIdRouteImport.update({
  id: '/$botId',
  path: '/$botId',
  getParentRoute: () => BuilderRoute,
} as any)
const BotBotIdRoute = BotBotIdRouteImport.update({
  id: '/bot/$botId',
  path: '/bot/$botId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteWithChildren
  '/widget.js': typeof WidgetDotjsRoute
  '/bot/$botId': typeof BotBotIdRoute
  '/builder/$botId': typeof BuilderBotIdRoute
  '/chat/$botId': typeof ChatBotIdRoute
  '/embed/$botId': typeof EmbedBotIdRoute
  '/widget/$botId': typeof WidgetBotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteWithChildren
  '/widget.js': typeof WidgetDotjsRoute
  '/bot/$botId': typeof BotBotIdRoute
  '/builder/$botId': typeof BuilderBotIdRoute
  '/chat/$botId': typeof ChatBotIdRoute
  '/embed/$botId': typeof EmbedBotIdRoute
  '/widget/$botId': typeof WidgetBotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteWithChildren
  '/widget.js': typeof WidgetDotjsRoute
  '/bot/$botId': typeof BotBotIdRoute
  '/builder/$botId': typeof BuilderBotIdRoute
  '/chat/$botId': typeof ChatBotIdRoute
  '/embed/$botId': typeof EmbedBotIdRoute
  '/widget/$botId': typeof WidgetBotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/widget.js'
    | '/bot/$botId'
    | '/builder/$botId'
    | '/chat/$botId'
    | '/embed/$botId'
    | '/widget/$botId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/widget.js'
    | '/bot/$botId'
    | '/builder/$botId'
    | '/chat/$botId'
    | '/embed/$botId'
    | '/widget/$botId'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/widget.js'
    | '/bot/$botId'
    | '/builder/$botId'
    | '/chat/$botId'
    | '/embed/$botId'
    | '/widget/$botId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRouteWithChildren
  WidgetDotjsRoute: typeof WidgetDotjsRoute
  BotBotIdRoute: typeof BotBotIdRoute
  ChatBotIdRoute: typeof ChatBotIdRoute
  EmbedBotIdRoute: typeof EmbedBotIdRoute
  WidgetBotIdRoute: typeof WidgetBotIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widget.js': {
      id: '/widget.js'
      path: '/widget.js'
      fullPath: '/widget.js'
      preLoaderRoute: typeof WidgetDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/$botId': {
      id: '/widget/$botId'
      path: '/widget/$botId'
      fullPath: '/widget/$botId'
      preLoaderRoute: typeof WidgetBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$botId': {
      id: '/embed/$botId'
      path: '/embed/$botId'
      fullPath: '/embed/$botId'
      preLoaderRoute: typeof EmbedBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$botId': {
      id: '/chat/$botId'
      path: '/chat/$botId'
      fullPath: '/chat/$botId'
      preLoaderRoute: typeof ChatBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$botId': {
      id: '/builder/$botId'
      path: '/$botId'
      fullPath: '/builder/$botId'
      preLoaderRoute: typeof BuilderBotIdRouteImport
      parentRoute: typeof BuilderRoute
    }
    '/bot/$botId': {
      id: '/bot/$botId'
      path: '/bot/$botId'
      fullPath: '/bot/$botId'
      preLoaderRoute: typeof BotBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BuilderRouteChildren {
  BuilderBotIdRoute: typeof BuilderBotIdRoute
}

const BuilderRouteChildren: BuilderRouteChildren = {
  BuilderBotIdRoute: BuilderBotIdRoute,
}

const BuilderRouteWithChildren =
  BuilderRoute._addFileChildren(BuilderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRouteWithChildren,
  WidgetDotjsRoute: WidgetDotjsRoute,
  BotBotIdRoute: BotBotIdRoute,
  ChatBotIdRoute: ChatBotIdRoute,
  EmbedBotIdRoute: EmbedBotIdRoute,
  WidgetBotIdRoute: WidgetBotIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
